export enum ROUTES {
    HOMEPAGE = "https://www.availproject.org/",
    DEVELOPERS = "https://www.availproject.org/developer",
    ABOUTUS = "https://www.availproject.org/aboutus",
    ECOSYSTEM = "https://www.availproject.org/ecosystem",
    SOLUTIONS = "https://www.availproject.org/solutions",
    TELEGRAM = "https://t.me/AvailCommunity",
    DISCORD = "https://discord.gg/AvailProject",
    GITHUB = "https://github.com/availproject",
    TWITTER = "https://twitter.com/AvailProject",
    LINKEDIN = "https://www.linkedin.com/company/availproject/",
    DOCUMENTATION = "https://docs.availproject.org/",
    API_DOCS = "https://docs.availproject.org/api-reference/avail-node-api",
    VALIDATOR = "https://docs.availproject.org/docs/operate-a-node/become-a-validator",
    FAUCET = "https://docs.availproject.org/docs/end-user-guide/faucet",
    EXPLORER = "https://docs.availproject.org/docs/end-user-guide/explorer",
    CAREERS = "https://avail.keka.com/careers",
    CLIENT_SETUP = "https://docs.availproject.org/docs/operate-a-node/run-a-light-client/0010-light-client",
    BECOME_VALIDATOR = "https://docs.availproject.org/category/become-a-validator/",
    COMMUNITY = "https://discord.gg/AvailProject",
    BLOG = "https://blog.availproject.org/",
    NETWORK = "https://docs.availproject.org/docs/networks",
    REFER_DOCS = "https://github.com/availproject/data-availability/blob/93c547ce4efce3e992b573179a8d22b3657fdcee/reference%20document/Avail%20Reference%20Paper%20v2.1%206%20Nov%202024.pdf",
    WORKING = "https://docs.availproject.org/join-the-network/node-types#validator-nodes",
  }