export enum ROUTES {
    HOMEPAGE = '/',
    DEVELOPERS = 'https://www.availproject.org/developer',
    ABOUTUS = 'https://www.availproject.org/aboutus',
    ECOSYSTEM = 'https://www.availproject.org/ecosystem',
    // SOLUTIONS = '/solutions',
    DISCORD = 'https://discord.gg/y6fHnxZQX8',
    GITHUB = 'https://github.com/availproject',
    TWITTER = 'https://twitter.com/AvailProject',
    LINKEDIN = 'https://www.linkedin.com/company/availproject/',
    DOCUMENTATION = 'https://availproject.github.io/',
    API_DOCS = 'https://availproject.github.io/using-avail/communicating-with-avail',
    VALIDATOR = 'https://availproject.github.io/join-the-network/run-avail/validator-node-setup',
    BECOME_VALIDATOR = 'https://docs.google.com/forms/d/e/1FAIpQLScpwE8yuUkqJVQrVpLRqua5p8oA8DGUBYho9Rwjm1bmG8LebQ/viewform',
    FAUCET = 'https://availproject.github.io/using-avail/getting-started/testnet-faucet',
    EXPLORER = 'https://availproject.github.io/using-avail/getting-started/avail-explorer',
    CAREERS = 'https://wellfound.com/company/avail-6/jobs',
    CLIENT_SETUP = 'https://availproject.github.io/join-the-network/run-avail/light-client-setup',
    COMMUNITY = 'https://discord.gg/y6fHnxZQX8',
    BLOG = 'https://blog.availproject.org/',
    NETWORK = 'https://availproject.github.io/join-the-network/networks',
    REFER_DOCS = 'https://github.com/availproject/data-availability/blob/master/reference%20document/Data%20Availability%20-%20Reference%20Document.pdf',
    WORKING = 'https://availproject.github.io/join-the-network/node-types#validator-nodes'
}